const ACCENT = '#d7ff32';
const BLUE   = '#6b9fff';

const S = {
  shell:      { background: '#0c0d10', color: '#e7e9ee', minHeight: '100vh', fontFamily: "'IBM Plex Mono', ui-monospace, monospace" },
  page:       { maxWidth: 540, margin: '0 auto', padding: '26px 18px 70px', animation: 'rise .25s ease' },
  kicker:     { fontSize: 11, letterSpacing: 3, color: ACCENT, fontWeight: 500 },
  h1:         { fontFamily: "'Oswald', sans-serif", fontWeight: 700, lineHeight: 1, margin: '6px 0 8px', letterSpacing: 1 },
  h2:         { fontFamily: "'Oswald', sans-serif", fontWeight: 700, margin: '4px 0 6px', letterSpacing: 1 },
  sub:        { color: '#8b909c', marginBottom: 22, lineHeight: 1.5 },
  cta:        { width: '100%', padding: '15px', background: ACCENT, color: '#0c0d10', border: 'none', borderRadius: 10, fontFamily: "'Oswald', sans-serif", fontWeight: 700, fontSize: 15, letterSpacing: 1, cursor: 'pointer', marginBottom: 10 },
  ghost:      { width: '100%', padding: '13px', background: 'transparent', color: '#cfd3dc', border: '1px solid #2a2e38', borderRadius: 10, fontFamily: "'Oswald', sans-serif", fontWeight: 500, fontSize: 14, letterSpacing: 1, cursor: 'pointer', marginBottom: 10 },
  label:      { fontSize: 11, letterSpacing: 2, color: '#8b909c', margin: '24px 0 10px' },
  empty:      { padding: '22px 16px', border: '1px dashed #2a2e38', borderRadius: 10, color: '#6b7080', fontSize: 13, textAlign: 'center', lineHeight: 1.6 },
  row:        { display: 'flex', alignItems: 'center', gap: 10, padding: '13px 14px', background: '#13151b', border: '1px solid #1d2027', borderRadius: 10, marginBottom: 8, cursor: 'pointer' },
  rowDate:    { fontSize: 11, color: ACCENT, marginBottom: 3, letterSpacing: 1 },
  rowName:    { fontFamily: "'Oswald', sans-serif", fontWeight: 500, fontSize: 17 },
  rowMeta:    { fontSize: 11, color: '#7b8090', marginTop: 3 },
  back:       { background: 'none', border: 'none', color: '#8b909c', fontSize: 13, padding: '4px 0', marginBottom: 8, cursor: 'pointer', fontFamily: 'inherit' },
  previewImg: { width: '100%', borderRadius: 12, border: '1px solid #1d2027', margin: '6px 0 16px' },
  previewThumb: { width: '100%', maxHeight: 150, objectFit: 'cover', borderRadius: 10, border: '1px solid #1d2027', margin: '6px 0 14px' },
  loading:    { display: 'flex', alignItems: 'center', gap: 12, padding: '20px 4px', color: '#cfd3dc', fontSize: 14 },
  spinner:    { width: 22, height: 22, border: '3px solid #2a2e38', borderTopColor: ACCENT, borderRadius: '50%', animation: 'spin .8s linear infinite' },
  errBox:     { marginTop: 12, padding: 12, background: '#1a1115', border: '1px solid #5a2330', borderRadius: 10, color: '#ff9aa6', fontSize: 12.5, lineHeight: 1.5 },
  inlineBtn:  { background: 'none', border: 'none', color: ACCENT, cursor: 'pointer', fontFamily: 'inherit', fontSize: 12.5, padding: 0 },
  input:      { width: '100%', padding: '12px 14px', background: '#13151b', border: '1px solid #20232b', borderRadius: 10, color: '#e7e9ee', fontSize: 14, marginBottom: 14 },
  dateInput:  { colorScheme: 'dark' },
  rowInputs:  { display: 'flex', gap: 10, alignItems: 'stretch' },
  card:       { background: '#11131a', border: '1px solid #1d2027', borderRadius: 12, padding: 14, marginBottom: 12 },
  cardHead:   { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 },
  exName:     { flex: 1, minWidth: 0, padding: '10px 12px', background: '#0c0d10', border: '1px solid #20232b', borderRadius: 8, color: '#e7e9ee', fontFamily: "'Oswald', sans-serif", fontWeight: 500, fontSize: 16 },
  exNameGuess:{ borderColor: ACCENT, boxShadow: '0 0 0 1px ' + ACCENT },
  confirmBtn: { width: 40, flexShrink: 0, padding: '8px 0', background: ACCENT, color: '#0c0d10', border: 'none', borderRadius: 8, fontSize: 16, fontWeight: 700, cursor: 'pointer' },
  // Modality badge
  modalityBadge: { display: 'inline-block', fontSize: 11, padding: '4px 10px', borderRadius: 20, border: '1px solid', cursor: 'pointer', marginBottom: 10, fontFamily: 'inherit', letterSpacing: 0.5 },
  modalityColors: {
    strength:   { background: 'rgba(215,255,50,0.08)',  color: ACCENT,    borderColor: 'rgba(215,255,50,0.3)' },
    bodyweight: { background: 'rgba(107,159,255,0.08)', color: BLUE,      borderColor: 'rgba(107,159,255,0.3)' },
    distance:   { background: 'rgba(255,178,71,0.08)',  color: '#ffb247', borderColor: 'rgba(255,178,71,0.3)' },
    duration:   { background: 'rgba(160,107,255,0.08)', color: '#a06bff', borderColor: 'rgba(160,107,255,0.3)' },
    cardio:     { background: 'rgba(71,225,178,0.08)',  color: '#47e1b2', borderColor: 'rgba(71,225,178,0.3)' },
  },
  setHeader:  { display: 'flex', alignItems: 'center', gap: 6, fontSize: 10, letterSpacing: 1, color: '#6b7080', marginBottom: 6, paddingLeft: 2 },
  col:        { flex: 1, minWidth: 0 },
  setRow:     { display: 'flex', alignItems: 'center', gap: 6, marginBottom: 7, overflow: 'hidden' },
  setNo:      { width: 20, flexShrink: 0, fontSize: 12, color: '#7b8090', textAlign: 'center' },
  setInput:   { flex: 1, minWidth: 0, padding: '9px 4px', background: '#0c0d10', border: '1px solid #20232b', borderRadius: 8, color: '#e7e9ee', fontSize: 14, textAlign: 'center' },
  unitBtn:    { width: 42, flexShrink: 0, padding: '9px 0', background: '#1a1d24', border: '1px solid #2a2e38', borderRadius: 8, color: ACCENT, fontFamily: 'inherit', fontSize: 11, cursor: 'pointer' },
  // Resistance stepper
  stepper:    { display: 'flex', alignItems: 'center', flexShrink: 0, background: '#1a1d24', border: '1px solid #2a2e38', borderRadius: 8, overflow: 'hidden' },
  stepBtn:    { width: 24, padding: '9px 0', background: 'transparent', border: 'none', color: '#8b909c', fontSize: 15, cursor: 'pointer', fontFamily: 'inherit' },
  stepVal:    { width: 20, textAlign: 'center', fontSize: 13, color: '#47e1b2' },
  del:        { background: 'none', border: 'none', color: '#6b7080', fontSize: 16, cursor: 'pointer', padding: '4px 6px', flexShrink: 0 },
  delSm:      { width: 24, flexShrink: 0, background: 'none', border: 'none', color: '#5a5f6b', fontSize: 13, cursor: 'pointer' },
  addSet:     { background: 'none', border: '1px dashed #2a2e38', borderRadius: 8, color: '#8b909c', fontFamily: 'inherit', fontSize: 12, padding: '8px', width: '100%', cursor: 'pointer', marginTop: 4 },
  guessBanner:{ background: 'rgba(215,255,50,0.08)', border: '1px solid rgba(215,255,50,0.35)', borderRadius: 10, padding: '11px 13px', fontSize: 12, color: '#d7ff32', lineHeight: 1.55, marginBottom: 14 },
  guessTag:   { fontSize: 11, color: '#aeb86b', margin: '-2px 0 8px 2px', lineHeight: 1.4 },
  rememberTag:{ fontSize: 11, color: '#6b7080', margin: '-2px 0 8px 2px', lineHeight: 1.4 },
  hintTag:    { fontSize: 11, color: '#7fbfa0', margin: '-2px 0 8px 2px', lineHeight: 1.4 },
  histTag:    { fontSize: 11, color: '#6b9fff', margin: '-2px 0 8px 2px', lineHeight: 1.4 },
  chipSm:     { padding: '5px 10px', fontSize: 10.5, letterSpacing: 0.5 },
  chips:      { display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  chip:       { padding: '7px 12px', background: '#13151b', border: '1px solid #2a2e38', borderRadius: 20, color: '#cfd3dc', fontFamily: 'inherit', fontSize: 12, cursor: 'pointer' },
  chipOn:     { background: ACCENT, color: '#0c0d10', borderColor: ACCENT, fontWeight: 500 },
  statRow:    { display: 'flex', gap: 8, marginBottom: 16 },
  statBox:    { flex: 1, background: '#11131a', border: '1px solid #1d2027', borderRadius: 10, padding: '10px 8px', textAlign: 'center' },
  statVal:    { fontFamily: "'Oswald', sans-serif", fontWeight: 700, fontSize: 20, color: '#e7e9ee', lineHeight: 1 },
  statUnit:   { fontSize: 11, color: '#8b909c', marginLeft: 2 },
  statLbl:    { fontSize: 9, letterSpacing: 1.5, color: '#6b7080', marginTop: 4 },
  toggle:     { display: 'flex', background: '#11131a', border: '1px solid #1d2027', borderRadius: 10, overflow: 'hidden', marginBottom: 14 },
  toggleBtn:  { flex: 1, padding: '10px', background: 'transparent', border: 'none', color: '#6b7080', fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, letterSpacing: 1.5, cursor: 'pointer' },
  toggleOn:   { background: '#1d2027', color: ACCENT },
  chartCaption: { fontSize: 11, color: '#6b7080', marginBottom: 2, lineHeight: 1.5 },
  chartNote:  { fontSize: 11, color: '#6b7080', marginTop: 10, lineHeight: 1.6, padding: '8px 10px', background: '#11131a', borderRadius: 8, border: '1px solid #1d2027' },
  chartLabel: { fontSize: 12, color: '#8b909c', letterSpacing: 1 },
  note:       { fontSize: 11, color: '#6b7080', marginTop: 16, textAlign: 'center' },
  dataRow:    { display: 'flex', gap: 8 },
  dataBtn:    { flex: 1, padding: '10px 0', background: 'transparent', border: '1px solid #2a2e38', borderRadius: 8, color: '#8b909c', fontFamily: 'inherit', fontSize: 12, cursor: 'pointer' },
  dataMsg:    { fontSize: 11.5, color: '#7fbfa0', marginTop: 10, lineHeight: 1.5 },
  dataNote:   { fontSize: 10.5, color: '#5a5f6b', marginTop: 10, lineHeight: 1.6 },
  logRow:     { background: '#11131a', border: '1px solid #1d2027', borderRadius: 8, padding: '9px 11px', marginBottom: 7 },
  logHead:    { display: 'flex', alignItems: 'baseline', gap: 8 },
  logLevel:   { fontSize: 10, letterSpacing: 1, textTransform: 'uppercase', flexShrink: 0 },
  logEvent:   { fontSize: 12, color: '#e7e9ee', flex: 1, minWidth: 0 },
  logTs:      { fontSize: 10, color: '#5a5f6b', flexShrink: 0 },
  logDetail:  { fontSize: 10.5, color: '#8b909c', marginTop: 4, lineHeight: 1.5, wordBreak: 'break-word' },
};

export { ACCENT, BLUE, S };
